exp_name: F5TTS_v1_Base
tokenizer: char
learning_rate: 1.0e-5
batch_size_per_gpu: 400
batch_size_type: frame
max_samples: 8
grad_accumulation_steps: 1
max_grad_norm: 1.0
epochs: 1
num_warmup_updates: 10
save_per_updates: 20
keep_last_n_checkpoints: 2
last_per_updates: 20
finetune: true
logger: tensorboard
log_samples: false
bnb_optimizer: false
val_ratio: 0.1
